vehicle_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from vehicle_inventory.forms import UserLoginForm, UserSigninForm
from vehicle_inventory.models import User, db, check_password_hash

# Imports for flask login
from flask_login import login_user, logout_user, login_required

templates = Blueprint('templates',__name__,template_folder='templates_folder')

@templates.route('/signup', methods = ['GET','POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            first_name = form.first_name.data
            last_name = form.last_name.data
            password = form.password.data
            print(email, password)

            user = User(email, first_name, last_name, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form Inputs')

    return render_template('signup.html', form = form)

@templates.route('/signin', methods = ['GET','POST'])
def signin():
    form = UserSigninForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first() 
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You have successfully logged in: via email/password', 'auth-success')
                return redirect(url_for('site.home'))
            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('templates.signin'))
    
    except:
        raise Exception('Invalid Form Data: Please Check Your Form!')
    return render_template('signin.html', form = form)    

@templates.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

vehicle_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

vehicle_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
<link rel="stylesheet" href="../static/main.css">
<title>Title</title>
</head>
<body>
    
    <!--Navbar Here-->
    <nav class="car-nav">
        <div>
            <img src="" alt="">
        </div>

        <!--Nav Items-->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>Car API</li>
                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>

                {% if current_user.is_authenticated %}
                <a href="{{ url_for('templates.logout') }}">
                    <li>Log Out</li>
                </a>

                {% else %}
                <a href="{{ url_for('templates.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('templates.signup') }}">
                    <li>Sign Up</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock content%}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"></script>
</body>
</html>

vehicle_inventory/templates/form.html
<!--HTML Produced By the Flask Form-->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">

        <fieldset id="first-name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = 'form-control', placeholder = "Enter First Name Here")}}
        </fieldset>

        <fieldset id="last-name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = 'form-control', placeholder = "Enter Last Name Here")}}
        </fieldset>

        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = "Place Email Here") }}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = 'form-control', placeholder = "Place Password Here")}}
        </fieldset>

        <!--Submit Button-->
        {{ form.submit_button(class = "btn btn-primary") }}
    </div>
</form>

vehicle_inventory/templates/form2.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">

        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = "Place Email Here") }}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = 'form-control', placeholder = "Place Password Here")}}
        </fieldset>

        <!--Submit Button-->
        {{ form.submit_button(class = "btn btn-primary") }}
    </div>
</form>